# Generated by Django 5.1.4 on 2024-12-07 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_App', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Library_User',
        ),
    ]
