# Generated by Django 5.1.4 on 2024-12-07 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_App', '0003_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='Borrow_Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('rejected', 'rejected')], default='pending', max_length=30)),
                ('requested_time', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LMS_App.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LMS_App.library_user')),
            ],
        ),
    ]
