# Generated by Django 5.1.4 on 2024-12-08 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_App', '0005_alter_book_file_alter_book_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow_request',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='borrow_request',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
